name: englishapp
description: "A new Flutter project English app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  provider: ^6.1.2
  color_type_converter: ^1.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  flutter_webrtc: ^0.11.1
  image_cropper: ^7.1.0
  flutter_widget_from_html: ^0.15.1
  flutter_quill: ^10.0.0
  google_ml_kit: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/res/l10n/
    - lib/res/assets/avatar.jpg
    - lib/res/assets/icons/flutter-icons-8db9be19/
    - lib/res/assets/icon_app/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: lib/res/assets/icons/flutter-icons-8db9be19/fonts/MyFlutterApp.ttf
