// lib/src/theme/colors.dart
import 'package:flutter/material.dart';
import 'package:color_type_converter/color_type_converter.dart';
import 'package:hexcolor/hexcolor.dart';

class AppColors {
  static const Map<int, Map<String, Color>> themes = {
    0: {
      'navigationBarBackground': Color(0xFF13112F),
      // 'navigationBarBackground': HexColor("#1F043A"),
      'chooseNavigationBarBackground': Color(0xFF000000),
      'pageBackground': Color(0xFF38036D),
      'cardBackground': Color(0xFF2D0259),
      'searchDictionaryBackground': Color(0xFFFF6A00),
      'cardChatBot': Color(0xFF38036D),
      'border': Color(0xFFD5D5D5),
      'continueSubscriptionBackground': Color(0xFFF5B000),
      'buttonContinueSubscription': Color(0xFFFFB700),
      'seeAllVocabularyList': Color(0xFFFF6A00),
      'messageUserBackground': Color(0xFF13112F),
      'studyThisSet': Color(0xFFFF8000),
      'messageBotBackground': Color(0xFF1E0101),
      'headerBackground': Color(0xFFFFA6DB),
      'buttonCall': Color(0xFFFF0000),
      'headerBackgroundProfile': Color(0xFFFF8200),
      'headerCircle1': Color(0xFFE1C9FF),
      'headerCircle2': Color(0xFFB57DFE),
      'headerCircle3': Color(0xFFD9D9D9),
      'primaryText': Colors.white,
      'primaryTextHeader': Colors.white,
      'secondaryText': Colors.white70,
      'chatBubbleBackground': Colors.blue,
      'footerBackground': Colors.blue,

    },
    1: {
      'navigationBarBackground': Color(0xFFFF39C7),
      // 'navigationBarBackground': HexColor("#FF69B4"),
      // 'navigationBarBackground': ColorConverter<Color>().convert('#D04CD9'),
      'chooseNavigationBarBackground': Color(0xFF000000),
      'pageBackground': Color(0xFFFFC0CB),
      'cardBackground': Color(0xFFFFB6C1),
      'searchDictionaryBackground': Color(0xFFFF6A00),
      'cardChatBot': Color(0xFFFFFFFF),
      'border': Color(0xFFD5D5D5),
      'continueSubscriptionBackground': Color(0xFFF5B000),
      'buttonContinueSubscription': Color(0xFFD98A19),
      'seeAllVocabularyList': Color(0xFFFF6A00),
      'messageUserBackground': Color(0xFFFF39C7),
      'studyThisSet': Color(0xFFFF8000),
      'messageBotBackground': Color(0xFFFF39C7),
      'headerBackground': Color(0xFFFFE4E1),
      'buttonCall': Color(0xFFFF0000),
      'headerBackgroundProfile': Color(0xFFFF8200),
      'headerCircle1': Color(0xFFFFDAB9),
      'headerCircle2': Color(0xFFFFA07A),
      'headerCircle3': Color(0xFFF08080),
      'primaryText': Colors.black,
      'primaryTextHeader': Colors.white,
      'secondaryText': Colors.black87,
      'chatBubbleBackground': Colors.pinkAccent,
      'footerBackground': Colors.pinkAccent,

    },
    2: {
      'navigationBarBackground': Color(0xFFFFFFFF),
      'chooseNavigationBarBackground': Color(0xFFFFA600),
      'pageBackground': Color(0xFFFFFFFF),
      'cardBackground': Color(0xFFFFFFFF),
      'searchDictionaryBackground': Color(0xFFFF8429),
      'cardChatBot': Color(0xFFFFFFFF),
      'border': Color(0xFFD5D5D5),
      'continueSubscriptionBackground': Color(0xFFF5B000),
      'buttonContinueSubscription': Color(0xFFFF6A00),
      'seeAllVocabularyList': Color(0xFFFF6A00),
      'messageUserBackground': Color(0xFFD98A19),
      'studyThisSet': Color(0xFFFF8000),
      'messageBotBackground': Color(0xFFF6810A),
      'headerBackground': Color(0xFFF5B000),
      'buttonCall': Color(0xFFFF0000),
      'headerBackgroundProfile': Color(0xFFFF9700),
      'headerCircle1': Color(0xFF00FF14),
      'headerCircle2': Color(0xFFFF0000),
      'headerCircle3': Color(0xFFA9A6A6),
      'headerCircle4': Color(0xFFFFE082),
      'primaryText': Colors.black,
      'primaryTextHeader': Colors.white,
      'secondaryText': Colors.black87,
      'chatBubbleBackground': Colors.amber,
      'footerBackground': Colors.amber,
    },
  };

  static Color getColor(int themeIndex, String colorKey) {
    return themes[themeIndex]?[colorKey] ?? Colors.black;
  }
}
