name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Update CocoaPods repository
        run: pod repo update
        working-directory: ios

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Create Payload Directory
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - name: Move App to Payload
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip IPA
        run: zip -r FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: FlutterIpaExport
          path: build/ios/iphoneos/FlutterIpaExport.ipa
