name: Build iOS Flutter App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install specific Flutter version
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.22.2
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build iOS IPA
        run: flutter build ipa --no-codesign
        env:
          FLUTTER_BUILD_NAME: 1.0.0
          FLUTTER_BUILD_NUMBER: 1

      - name: Archive the build
        run: |
          cd build/ios/archive
          zip -r app.zip Runner.xcarchive

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iOS-build
          path: build/ios/archive/app.zip